routes/web.php
    /*
    |--------------------------------------------------------------------------
    | Pelaksana
    |--------------------------------------------------------------------------
    */
     Route::get('/pelaksana', 'Pelaksana\PelaksanaController@index');
     Route::get('/pelaksana/surtu', 'Pelaksana\PelaksanaController@surtu');
     Route::get('/pelaksana/surtu/{id}', 'Pelaksana\PelaksanaController@surtu_show');
     Route::get('/pelaksana/laporan', 'Pelaksana\PelaksanaController@laporan');
     Route::get('/pelaksana/laporan/{id}', 'Pelaksana\PelaksanaController@laporan_show');
     Route::get('/pelaksana/createlaporan/{id}', 'Pelaksana\PelaksanaController@laporan_add');

    /*
    |--------------------------------------------------------------------------
    | Letter Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letters', 'LettersController', ['except' => ['show', 'delete']]);
    Route::post('letters/search', [
        'as' => 'letters.search',
        'uses' => 'LettersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Recipient Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('recipients', 'RecipientsController', ['except' => ['show', 'delete']]);
    Route::post('recipients/search', [
        'as' => 'recipients.search',
        'uses' => 'RecipientsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lettertype Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('lettertypes', 'LettertypesController', ['except' => ['show', 'delete']]);
    Route::post('lettertypes/search', [
        'as' => 'lettertypes.search',
        'uses' => 'LettertypesController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Letterattachment Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letterattachments', 'LetterattachmentsController', ['except' => ['show', 'delete']]);
    Route::post('letterattachments/search', [
        'as' => 'letterattachments.search',
        'uses' => 'LetterattachmentsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lettertype Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('lettertypes', 'LettertypesController', ['except' => ['show', 'delete']]);
    Route::post('lettertypes/search', [
        'as' => 'lettertypes.search',
        'uses' => 'LettertypesController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Letterattachment Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letterattachments', 'LetterattachmentsController', ['except' => ['show', 'delete']]);
    Route::post('letterattachments/search', [
        'as' => 'letterattachments.search',
        'uses' => 'LetterattachmentsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Letterattachmentletter Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letterattachmentletters', 'LetterattachmentlettersController', ['except' => ['show', 'delete']]);
    Route::post('letterattachmentletters/search', [
        'as' => 'letterattachmentletters.search',
        'uses' => 'LetterattachmentlettersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Agendanumber Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('agendanumbers', 'AgendanumbersController', ['except' => ['show', 'delete']]);
    Route::post('agendanumbers/search', [
        'as' => 'agendanumbers.search',
        'uses' => 'AgendanumbersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Agendanumberuser Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('agendanumberusers', 'AgendanumberusersController', ['except' => ['show', 'delete']]);
    Route::post('agendanumberusers/search', [
        'as' => 'agendanumberusers.search',
        'uses' => 'AgendanumberusersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Jabatan Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('jabatans', 'JabatansController', ['except' => ['show', 'delete']]);
    Route::post('jabatans/search', [
        'as' => 'jabatans.search',
        'uses' => 'JabatansController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Departement Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('departements', 'DepartementsController', ['except' => ['show', 'delete']]);
    Route::post('departements/search', [
        'as' => 'departements.search',
        'uses' => 'DepartementsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lettersource Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('lettersources', 'LettersourcesController', ['except' => ['show', 'delete']]);
    Route::post('lettersources/search', [
        'as' => 'lettersources.search',
        'uses' => 'LettersourcesController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Anggaran Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('anggarans', 'AnggaransController', ['except' => ['show', 'delete']]);
    Route::post('anggarans/search', [
        'as' => 'anggarans.search',
        'uses' => 'AnggaransController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Material Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('materials', 'MaterialsController', ['except' => ['show', 'delete']]);
    Route::post('materials/search', [
        'as' => 'materials.search',
        'uses' => 'MaterialsController@search'
    ]);


    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', function(){ return Redirect::to('cms/dashboard'); });

    

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

        Route::get('dashboard', 'DashboardController@index');

        /*
        |--------------------------------------------------------------------------
        | Users
        |--------------------------------------------------------------------------
        */
        Route::resource('users', 'UserController', ['except' => ['show']]);
        Route::post('users/search', 'UserController@search');
        Route::get('users/search', 'UserController@index');
        Route::get('users/invite', 'UserController@getInvite');
        Route::get('users/switch/{id}', 'UserController@switchToUser');
        Route::post('users/invite', 'UserController@postInvite');
        Route::post('users/store', 'UserController@store');
        Route::post('users/searchcompany', 'UserController@searchcompany');
        Route::get('users/upload', 'UserController@upload');
        Route::post('users/import', 'UserController@import');

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */
        Route::resource('roles', 'RoleController', ['except' => ['show']]);
        Route::post('roles/search', 'RoleController@search');
        Route::get('roles/search', 'RoleController@index');
        /*
        |--------------------------------------------------------------------------
        | Company Routes
        |--------------------------------------------------------------------------
        */
        Route::resource('companies', 'CompaniesController', ['except' => ['show']]);
        Route::post('companies/search', [
            'as' => 'companies.search',
            'uses' => 'CompaniesController@search'
        ]);
    });
});

app/Models/Letterattachmentletter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Letterattachmentletter extends Model
{
    public $table = "letterattachmentletters";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
		'lt_attachment_id',
		'lt_letter_id',

    ];

    public static $rules = [
        // create rules
    ];

    // Letterattachmentletter 
}

app/Http/Controllers/LetterattachmentlettersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\LetterattachmentletterService;
use App\Http\Requests\LetterattachmentletterCreateRequest;
use App\Http\Requests\LetterattachmentletterUpdateRequest;

class LetterattachmentlettersController extends Controller
{
    public function __construct(LetterattachmentletterService $letterattachmentletter_service)
    {
        $this->service = $letterattachmentletter_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $letterattachmentletters = $this->service->paginated();
        return view('letterattachmentletters.index')->with('letterattachmentletters', $letterattachmentletters);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $letterattachmentletters = $this->service->search($request->search);
        return view('letterattachmentletters.index')->with('letterattachmentletters', $letterattachmentletters);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('letterattachmentletters.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\LetterattachmentletterCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LetterattachmentletterCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('letterattachmentletters.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('letterattachmentletters.index'))->withErrors('Failed to create');
    }

    /**
     * Display the letterattachmentletter.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $letterattachmentletter = $this->service->find($id);
        return view('letterattachmentletters.show')->with('letterattachmentletter', $letterattachmentletter);
    }

    /**
     * Show the form for editing the letterattachmentletter.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $letterattachmentletter = $this->service->find($id);
        return view('letterattachmentletters.edit')->with('letterattachmentletter', $letterattachmentletter);
    }

    /**
     * Update the letterattachmentletters in storage.
     *
     * @param  App\Http\Requests\LetterattachmentletterUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(LetterattachmentletterUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->withErrors('Failed to update');
    }

    /**
     * Remove the letterattachmentletters from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('letterattachmentletters.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('letterattachmentletters.index'))->withErrors('Failed to delete');
    }
}

resources/views/letterattachmentletters/create.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Letterattachmentletters &raquo; Create'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'letterattachmentletters.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Letterattachmentletters: Create</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            {!! Form::open(['route' => 'letterattachmentletters.store']) !!}

            @form_maker_table("letterattachmentletters")

            {!! Form::submit('Save', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

@stop

resources/views/letterattachmentletters/edit.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Letterattachmentletters &raquo; Edit'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'letterattachmentletters.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Letterattachmentletters: Edit</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('letterattachmentletters.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            {!! Form::model($letterattachmentletter, ['route' => ['letterattachmentletters.update', $letterattachmentletter->id], 'method' => 'patch']) !!}

            @form_maker_object($letterattachmentletter, FormMaker::getTableColumns('letterattachmentletters'))

            {!! Form::submit('Update', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

@stop

resources/views/letterattachmentletters/index.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Letterattachmentletters &raquo; Index'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'letterattachmentletters.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Letterattachmentletters</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('letterattachmentletters.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @if ($letterattachmentletters->isEmpty())
                <div class="well text-center">No letterattachmentletters found.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th class="text-right" width="200px">Action</th>
                    </thead>
                    <tbody>
                        @foreach($letterattachmentletters as $letterattachmentletter)
                            <tr>
                                <td>
                                    <a href="{!! route('letterattachmentletters.edit', [$letterattachmentletter->id]) !!}">{{ $letterattachmentletter->name }}</a>
                                </td>
                                <td class="text-right">
                                    <form method="post" action="{!! route('letterattachmentletters.destroy', [$letterattachmentletter->id]) !!}">
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this letterattachmentletter?')"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                    <a class="btn btn-default btn-xs pull-right raw-margin-right-16" href="{!! route('letterattachmentletters.edit', [$letterattachmentletter->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $letterattachmentletters; !!}
        </div>
    </div>

@stop

resources/views/letterattachmentletters/show.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Letterattachmentletters &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop