routes/web.php
     Route::post('/manajer/storespk', [
        'as' => 'manajer.storespk',
        'uses' => 'Manajer\ManajerController@spk_add'
    ]);

     Route::get('/manajer/spk/{id}', 'Manajer\ManajerController@spk_show');
     Route::get('/manajer/laporan', 'Manajer\ManajerController@laporan');
     Route::get('/manajer/laporan/{id}', 'Manajer\ManajerController@laporan_show');

    /*
    |--------------------------------------------------------------------------
    | Supervisor
    |--------------------------------------------------------------------------
    */

     Route::get('/supervisor', 'Supervisor\SupervisorController@index');
     Route::get('/supervisor/spk', 'Supervisor\SupervisorController@spk');
     Route::get('/supervisor/spk/{id}', 'Supervisor\SupervisorController@spk_show');
     Route::get('/supervisor/surtu', 'Supervisor\SupervisorController@surtu');
     Route::get('/supervisor/surtu/{id}', 'Supervisor\SupervisorController@surtu_show');
     Route::get('/supervisor/createsurtu/{id}', 'Supervisor\SupervisorController@surtu_add');
     Route::post('/supervisor/surtu/store', 'Supervisor\SupervisorController@surtu_store');


     Route::get('/supervisor/laporan', 'Supervisor\SupervisorController@laporan');
     Route::get('/supervisor/laporan/{id}', 'Supervisor\SupervisorController@laporan_show');
     Route::get('/supervisor/createlaporan/{id}', 'Supervisor\SupervisorController@laporan_add');
     Route::post('/supervisor/laporan/store', 'Supervisor\SupervisorController@laporan_store');
     Route::get('/supervisor/laporanpelaksana', 'Supervisor\SupervisorController@laporanpelaksana');
     Route::get('/supervisor/laporanpelaksana/{id}', 'Supervisor\SupervisorController@laporanpelaksana_show');


    /*
    |--------------------------------------------------------------------------
    | Pelaksana
    |--------------------------------------------------------------------------
    */
     Route::get('/pelaksana', 'Pelaksana\PelaksanaController@index');
     Route::get('/pelaksana/surtu', 'Pelaksana\PelaksanaController@surtu');
     Route::get('/pelaksana/surtu/{id}', 'Pelaksana\PelaksanaController@surtu_show');
     Route::get('/pelaksana/laporan', 'Pelaksana\PelaksanaController@laporan');
     Route::get('/pelaksana/laporan/{id}', 'Pelaksana\PelaksanaController@laporan_show');
     Route::get('/pelaksana/createlaporan/{id}', 'Pelaksana\PelaksanaController@laporan_add');

    /*
    |--------------------------------------------------------------------------
    | Letter Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letters', 'LettersController', ['except' => ['show', 'delete']]);
    Route::post('letters/search', [
        'as' => 'letters.search',
        'uses' => 'LettersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Recipient Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('recipients', 'RecipientsController', ['except' => ['show', 'delete']]);
    Route::post('recipients/search', [
        'as' => 'recipients.search',
        'uses' => 'RecipientsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lettertype Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('lettertypes', 'LettertypesController', ['except' => ['show', 'delete']]);
    Route::post('lettertypes/search', [
        'as' => 'lettertypes.search',
        'uses' => 'LettertypesController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Letterattachment Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letterattachments', 'LetterattachmentsController', ['except' => ['show', 'delete']]);
    Route::post('letterattachments/search', [
        'as' => 'letterattachments.search',
        'uses' => 'LetterattachmentsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lettertype Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('lettertypes', 'LettertypesController', ['except' => ['show', 'delete']]);
    Route::post('lettertypes/search', [
        'as' => 'lettertypes.search',
        'uses' => 'LettertypesController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Letterattachment Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letterattachments', 'LetterattachmentsController', ['except' => ['show', 'delete']]);
    Route::post('letterattachments/search', [
        'as' => 'letterattachments.search',
        'uses' => 'LetterattachmentsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Letterattachmentletter Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('letterattachmentletters', 'LetterattachmentlettersController', ['except' => ['show', 'delete']]);
    Route::post('letterattachmentletters/search', [
        'as' => 'letterattachmentletters.search',
        'uses' => 'LetterattachmentlettersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Agendanumber Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('agendanumbers', 'AgendanumbersController', ['except' => ['show', 'delete']]);
    Route::post('agendanumbers/search', [
        'as' => 'agendanumbers.search',
        'uses' => 'AgendanumbersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Agendanumberuser Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('agendanumberusers', 'AgendanumberusersController', ['except' => ['show', 'delete']]);
    Route::post('agendanumberusers/search', [
        'as' => 'agendanumberusers.search',
        'uses' => 'AgendanumberusersController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Jabatan Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('jabatans', 'JabatansController', ['except' => ['show', 'delete']]);
    Route::post('jabatans/search', [
        'as' => 'jabatans.search',
        'uses' => 'JabatansController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Departement Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('departements', 'DepartementsController', ['except' => ['show', 'delete']]);
    Route::post('departements/search', [
        'as' => 'departements.search',
        'uses' => 'DepartementsController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Lettersource Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('lettersources', 'LettersourcesController', ['except' => ['show', 'delete']]);
    Route::post('lettersources/search', [
        'as' => 'lettersources.search',
        'uses' => 'LettersourcesController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Anggaran Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('anggarans', 'AnggaransController', ['except' => ['show', 'delete']]);
    Route::post('anggarans/search', [
        'as' => 'anggarans.search',
        'uses' => 'AnggaransController@search'
    ]);

    /*
    |--------------------------------------------------------------------------
    | Material Routes
    |--------------------------------------------------------------------------
    */

    Route::resource('materials', 'MaterialsController', ['except' => ['show', 'delete']]);
    Route::post('materials/search', [
        'as' => 'materials.search',
        'uses' => 'MaterialsController@search'
    ]);


    /*
    |--------------------------------------------------------------------------
    | General
    |--------------------------------------------------------------------------
    */

    Route::get('/users/switch-back', 'Admin\UserController@switchUserBack');

    /*
    |--------------------------------------------------------------------------
    | User
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
        Route::get('settings', 'SettingsController@settings');
        Route::post('settings', 'SettingsController@update');
        Route::get('password', 'PasswordController@password');
        Route::post('password', 'PasswordController@update');
    });

    /*
    |--------------------------------------------------------------------------
    | Dashboard
    |--------------------------------------------------------------------------
    */

    Route::get('/dashboard', function(){ return Redirect::to('cms/dashboard'); });

    

    /*
    |--------------------------------------------------------------------------
    | Admin
    |--------------------------------------------------------------------------
    */

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {

app/Http/Controllers/LettertypesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\LettertypeService;
use App\Http\Requests\LettertypeCreateRequest;
use App\Http\Requests\LettertypeUpdateRequest;

class LettertypesController extends Controller
{
    public function __construct(LettertypeService $lettertype_service)
    {
        $this->service = $lettertype_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $lettertypes = $this->service->paginated();
        return view('lettertypes.index')->with('lettertypes', $lettertypes);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $lettertypes = $this->service->search($request->search);
        return view('lettertypes.index')->with('lettertypes', $lettertypes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('lettertypes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\LettertypeCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LettertypeCreateRequest $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return redirect(route('lettertypes.edit', ['id' => $result->id]))->with('message', 'Successfully created');
        }

        return redirect(route('lettertypes.index'))->withErrors('Failed to create');
    }

    /**
     * Display the lettertype.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $lettertype = $this->service->find($id);
        return view('lettertypes.show')->with('lettertype', $lettertype);
    }

    /**
     * Show the form for editing the lettertype.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $lettertype = $this->service->find($id);
        return view('lettertypes.edit')->with('lettertype', $lettertype);
    }

    /**
     * Update the lettertypes in storage.
     *
     * @param  App\Http\Requests\LettertypeUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(LettertypeUpdateRequest $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return back()->with('message', 'Successfully updated');
        }

        return back()->withErrors('Failed to update');
    }

    /**
     * Remove the lettertypes from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return redirect(route('lettertypes.index'))->with('message', 'Successfully deleted');
        }

        return redirect(route('lettertypes.index'))->withErrors('Failed to delete');
    }
}

resources/views/lettertypes/create.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Lettertypes &raquo; Create'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'lettertypes.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Lettertypes: Create</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            {!! Form::open(['route' => 'lettertypes.store']) !!}

            @form_maker_table("lettertypes")

            {!! Form::submit('Save', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

@stop

resources/views/lettertypes/edit.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Lettertypes &raquo; Edit'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'lettertypes.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Lettertypes: Edit</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('lettertypes.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            {!! Form::model($lettertype, ['route' => ['lettertypes.update', $lettertype->id], 'method' => 'patch']) !!}

            @form_maker_object($lettertype, FormMaker::getTableColumns('lettertypes'))

            {!! Form::submit('Update', ['class' => 'btn btn-primary pull-right']) !!}

            {!! Form::close() !!}

        </div>
    </div>

@stop

resources/views/lettertypes/index.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Lettertypes &raquo; Index'])

@section('content')

    <div class="row">
        <div class="col-md-12">
            <div class="pull-right raw-margin-top-24 raw-margin-left-24">
                {!! Form::open(['route' => 'lettertypes.search']) !!}
                <input class="form-control form-inline pull-right" name="search" placeholder="Search">
                {!! Form::close() !!}
            </div>
            <h1 class="pull-left">Lettertypes</h1>
            <a class="btn btn-primary pull-right raw-margin-top-24 raw-margin-right-8" href="{!! route('lettertypes.create') !!}">Add New</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @if ($lettertypes->isEmpty())
                <div class="well text-center">No lettertypes found.</div>
            @else
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th class="text-right" width="200px">Action</th>
                    </thead>
                    <tbody>
                        @foreach($lettertypes as $lettertype)
                            <tr>
                                <td>
                                    <a href="{!! route('lettertypes.edit', [$lettertype->id]) !!}">{{ $lettertype->name }}</a>
                                </td>
                                <td class="text-right">
                                    <form method="post" action="{!! route('lettertypes.destroy', [$lettertype->id]) !!}">
                                        {!! csrf_field() !!}
                                        {!! method_field('DELETE') !!}
                                        <button class="btn btn-danger btn-xs pull-right" type="submit" onclick="return confirm('Are you sure you want to delete this lettertype?')"><i class="fa fa-trash"></i> Delete</button>
                                    </form>
                                    <a class="btn btn-default btn-xs pull-right raw-margin-right-16" href="{!! route('lettertypes.edit', [$lettertype->id]) !!}"><i class="fa fa-pencil"></i> Edit</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center">
            {!! $lettertypes; !!}
        </div>
    </div>

@stop

resources/views/lettertypes/show.blade.php
@extends('cms::layouts.dashboard', ['pageTitle' => 'Lettertypes &raquo; Show'])

@section('content')

    <div class="container">
        <div class="col-md-12">

        <!-- Put fields here -->

        </div>
    </div>

@stop